// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmp5ofC6lOKmGxESLZCwXxWI-2MNjxmv4',
    appId: '1:743253914783:web:9888859a197c4a99041eaa',
    messagingSenderId: '743253914783',
    projectId: 'numonics-226e1',
    authDomain: 'numonics-226e1.firebaseapp.com',
    storageBucket: 'numonics-226e1.firebasestorage.app',
    measurementId: 'G-4QXT7RTPPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArwxeHTfDvi-PH6gyom8Pp8M9rY2MLPaA',
    appId: '1:743253914783:android:516dd066ac203592041eaa',
    messagingSenderId: '743253914783',
    projectId: 'numonics-226e1',
    storageBucket: 'numonics-226e1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC88yJBqYLaV0l1-7Fb-i-ZFqKUXMid6dI',
    appId: '1:743253914783:ios:4c3f0911c7d33c1c041eaa',
    messagingSenderId: '743253914783',
    projectId: 'numonics-226e1',
    storageBucket: 'numonics-226e1.firebasestorage.app',
    iosBundleId: 'com.numonics.app',
  );
}
